baseURL = "https://azeem.dev/"
languageCode = "en-us"
title = "Azeem Chaudhry"
theme = "swiss-operator"

[markup.highlight]
style = "github-dark"
lineNos = true
[markup.goldmark.renderer]
  unsafe = true
